# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenerateReportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerateReportDialog(object):
    def setupUi(self, GenerateReportDialog):
        GenerateReportDialog.setObjectName("GenerateReportDialog")
        GenerateReportDialog.resize(449, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GenerateReportDialog.sizePolicy().hasHeightForWidth())
        GenerateReportDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(GenerateReportDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.turner_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.turner_checkBox.setChecked(False)
        self.turner_checkBox.setObjectName("turner_checkBox")
        self.gridLayout.addWidget(self.turner_checkBox, 4, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(GenerateReportDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.start_dateEdit = QtWidgets.QDateEdit(GenerateReportDialog)
        self.start_dateEdit.setObjectName("start_dateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.start_dateEdit)
        self.label_4 = QtWidgets.QLabel(GenerateReportDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.end_dateEdit = QtWidgets.QDateEdit(GenerateReportDialog)
        self.end_dateEdit.setObjectName("end_dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.end_dateEdit)
        self.gridLayout.addLayout(self.formLayout, 7, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 1, 1, 1)
        self.mentor_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.mentor_checkBox.setObjectName("mentor_checkBox")
        self.gridLayout.addWidget(self.mentor_checkBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(GenerateReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.generateButton = QtWidgets.QPushButton(GenerateReportDialog)
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.generateButton, 14, 1, 1, 1)
        self.team_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.team_checkBox.setObjectName("team_checkBox")
        self.gridLayout.addWidget(self.team_checkBox, 3, 2, 1, 1)
        self.line = QtWidgets.QFrame(GenerateReportDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 13, 0, 1, 3)
        self.other_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.other_checkBox.setObjectName("other_checkBox")
        self.gridLayout.addWidget(self.other_checkBox, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sortTime_radioButton = QtWidgets.QRadioButton(GenerateReportDialog)
        self.sortTime_radioButton.setObjectName("sortTime_radioButton")
        self.horizontalLayout.addWidget(self.sortTime_radioButton)
        self.sortID_radioButton = QtWidgets.QRadioButton(GenerateReportDialog)
        self.sortID_radioButton.setObjectName("sortID_radioButton")
        self.horizontalLayout.addWidget(self.sortID_radioButton)
        self.sortLength_radioButton = QtWidgets.QRadioButton(GenerateReportDialog)
        self.sortLength_radioButton.setObjectName("sortLength_radioButton")
        self.horizontalLayout.addWidget(self.sortLength_radioButton)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 3)
        self.dawson_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.dawson_checkBox.setChecked(False)
        self.dawson_checkBox.setObjectName("dawson_checkBox")
        self.gridLayout.addWidget(self.dawson_checkBox, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(GenerateReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 1, 1, 1)
        self.teacher_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.teacher_checkBox.setObjectName("teacher_checkBox")
        self.gridLayout.addWidget(self.teacher_checkBox, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(GenerateReportDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(GenerateReportDialog)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.alumni_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.alumni_checkBox.setObjectName("alumni_checkBox")
        self.gridLayout.addWidget(self.alumni_checkBox, 2, 2, 1, 1)
        self.pearland_checkBox = QtWidgets.QCheckBox(GenerateReportDialog)
        self.pearland_checkBox.setChecked(False)
        self.pearland_checkBox.setObjectName("pearland_checkBox")
        self.gridLayout.addWidget(self.pearland_checkBox, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(GenerateReportDialog)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 1, 1, 1)
        self.spacerLabel = QtWidgets.QLabel(GenerateReportDialog)
        self.spacerLabel.setText("")
        self.spacerLabel.setObjectName("spacerLabel")
        self.gridLayout.addWidget(self.spacerLabel, 1, 0, 1, 1)

        self.retranslateUi(GenerateReportDialog)
        QtCore.QMetaObject.connectSlotsByName(GenerateReportDialog)

    def retranslateUi(self, GenerateReportDialog):
        _translate = QtCore.QCoreApplication.translate
        GenerateReportDialog.setWindowTitle(_translate("GenerateReportDialog", "Generate Report"))
        self.turner_checkBox.setText(_translate("GenerateReportDialog", "Student (Turner)"))
        self.label_3.setText(_translate("GenerateReportDialog", "Start Date:"))
        self.label_4.setText(_translate("GenerateReportDialog", "End Date:"))
        self.mentor_checkBox.setText(_translate("GenerateReportDialog", "Mentor"))
        self.label_2.setText(_translate("GenerateReportDialog", "Date Range"))
        self.generateButton.setText(_translate("GenerateReportDialog", "Generate"))
        self.team_checkBox.setText(_translate("GenerateReportDialog", "Team"))
        self.other_checkBox.setText(_translate("GenerateReportDialog", "Other"))
        self.sortTime_radioButton.setText(_translate("GenerateReportDialog", "Sort by Time In"))
        self.sortID_radioButton.setText(_translate("GenerateReportDialog", "Sort by ID"))
        self.sortLength_radioButton.setText(_translate("GenerateReportDialog", "Sort by Time Length"))
        self.dawson_checkBox.setText(_translate("GenerateReportDialog", "Student (Dawson)"))
        self.label_5.setText(_translate("GenerateReportDialog", "Sort Mode"))
        self.teacher_checkBox.setText(_translate("GenerateReportDialog", "Teacher"))
        self.label.setText(_translate("GenerateReportDialog", "Categories to Include"))
        self.alumni_checkBox.setText(_translate("GenerateReportDialog", "Alumni"))
        self.pearland_checkBox.setText(_translate("GenerateReportDialog", "Student (Pearland)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GenerateReportDialog = QtWidgets.QDialog()
    ui = Ui_GenerateReportDialog()
    ui.setupUi(GenerateReportDialog)
    GenerateReportDialog.show()
    sys.exit(app.exec_())
