# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptionsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_optionsDialog(object):
    def setupUi(self, optionsDialog):
        optionsDialog.setObjectName("optionsDialog")
        optionsDialog.resize(888, 601)
        self.tabWidget = QtWidgets.QTabWidget(optionsDialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 891, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.log_rules_tab = QtWidgets.QWidget()
        self.log_rules_tab.setObjectName("log_rules_tab")
        self.tabWidget.addTab(self.log_rules_tab, "")
        self.leaderboard_tab = QtWidgets.QWidget()
        self.leaderboard_tab.setObjectName("leaderboard_tab")
        self.label = QtWidgets.QLabel(self.leaderboard_tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.student_dawson_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.student_dawson_checkBox.setGeometry(QtCore.QRect(30, 50, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.student_dawson_checkBox.setFont(font)
        self.student_dawson_checkBox.setObjectName("student_dawson_checkBox")
        self.student_pearland_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.student_pearland_checkBox.setGeometry(QtCore.QRect(30, 80, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.student_pearland_checkBox.setFont(font)
        self.student_pearland_checkBox.setObjectName("student_pearland_checkBox")
        self.student_turner_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.student_turner_checkBox.setGeometry(QtCore.QRect(30, 110, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.student_turner_checkBox.setFont(font)
        self.student_turner_checkBox.setObjectName("student_turner_checkBox")
        self.alumni_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.alumni_checkBox.setGeometry(QtCore.QRect(30, 140, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.alumni_checkBox.setFont(font)
        self.alumni_checkBox.setObjectName("alumni_checkBox")
        self.mentor_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.mentor_checkBox.setGeometry(QtCore.QRect(30, 170, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.mentor_checkBox.setFont(font)
        self.mentor_checkBox.setObjectName("mentor_checkBox")
        self.teacher_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.teacher_checkBox.setGeometry(QtCore.QRect(30, 200, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.teacher_checkBox.setFont(font)
        self.teacher_checkBox.setObjectName("teacher_checkBox")
        self.team_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.team_checkBox.setGeometry(QtCore.QRect(30, 230, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.team_checkBox.setFont(font)
        self.team_checkBox.setObjectName("team_checkBox")
        self.other_checkBox = QtWidgets.QCheckBox(self.leaderboard_tab)
        self.other_checkBox.setGeometry(QtCore.QRect(30, 260, 151, 21))
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(11)
        self.other_checkBox.setFont(font)
        self.other_checkBox.setObjectName("other_checkBox")
        self.tabWidget.addTab(self.leaderboard_tab, "")
        self.pushButton = QtWidgets.QPushButton(optionsDialog)
        self.pushButton.setGeometry(QtCore.QRect(750, 570, 121, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(optionsDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(optionsDialog)

    def retranslateUi(self, optionsDialog):
        _translate = QtCore.QCoreApplication.translate
        optionsDialog.setWindowTitle(_translate("optionsDialog", "Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_rules_tab), _translate("optionsDialog", "Log Rules"))
        self.label.setText(_translate("optionsDialog", "Visible Categories"))
        self.student_dawson_checkBox.setText(_translate("optionsDialog", "Student (Dawson)"))
        self.student_pearland_checkBox.setText(_translate("optionsDialog", "Student (Pearland)"))
        self.student_turner_checkBox.setText(_translate("optionsDialog", "Student (Turner)"))
        self.alumni_checkBox.setText(_translate("optionsDialog", "Alumni"))
        self.mentor_checkBox.setText(_translate("optionsDialog", "Mentor"))
        self.teacher_checkBox.setText(_translate("optionsDialog", "Teacher"))
        self.team_checkBox.setText(_translate("optionsDialog", "Team"))
        self.other_checkBox.setText(_translate("optionsDialog", "Other"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.leaderboard_tab), _translate("optionsDialog", "Leaderboard"))
        self.pushButton.setText(_translate("optionsDialog", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    optionsDialog = QtWidgets.QDialog()
    ui = Ui_optionsDialog()
    ui.setupUi(optionsDialog)
    optionsDialog.show()
    sys.exit(app.exec_())

