# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PearLog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        mainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("G:/Private/Pictures/Pearadox Logo.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background-color: rgb(230,230,230)")
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.studentTable = QtWidgets.QTableWidget(self.centralwidget)
        self.studentTable.setGeometry(QtCore.QRect(10, 0, 1532, 682))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentTable.sizePolicy().hasHeightForWidth())
        self.studentTable.setSizePolicy(sizePolicy)
        self.studentTable.setAlternatingRowColors(False)
        self.studentTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.studentTable.setGridStyle(QtCore.Qt.DotLine)
        self.studentTable.setWordWrap(False)
        self.studentTable.setCornerButtonEnabled(False)
        self.studentTable.setRowCount(4)
        self.studentTable.setColumnCount(9)
        self.studentTable.setObjectName("studentTable")
        self.studentTable.horizontalHeader().setVisible(False)
        self.studentTable.horizontalHeader().setDefaultSectionSize(170)
        self.studentTable.horizontalHeader().setHighlightSections(False)
        self.studentTable.verticalHeader().setVisible(False)
        self.studentTable.verticalHeader().setDefaultSectionSize(170)
        self.studentTable.verticalHeader().setHighlightSections(False)
        self.mentorTable = QtWidgets.QTableWidget(self.centralwidget)
        self.mentorTable.setGeometry(QtCore.QRect(10, 690, 1532, 342))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mentorTable.sizePolicy().hasHeightForWidth())
        self.mentorTable.setSizePolicy(sizePolicy)
        self.mentorTable.setAlternatingRowColors(False)
        self.mentorTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.mentorTable.setShowGrid(True)
        self.mentorTable.setGridStyle(QtCore.Qt.DotLine)
        self.mentorTable.setWordWrap(False)
        self.mentorTable.setCornerButtonEnabled(False)
        self.mentorTable.setRowCount(2)
        self.mentorTable.setColumnCount(9)
        self.mentorTable.setObjectName("mentorTable")
        self.mentorTable.horizontalHeader().setVisible(False)
        self.mentorTable.horizontalHeader().setDefaultSectionSize(170)
        self.mentorTable.verticalHeader().setVisible(False)
        self.mentorTable.verticalHeader().setDefaultSectionSize(170)
        self.mentorTable.verticalHeader().setHighlightSections(True)
        self.mentorTable.verticalHeader().setStretchLastSection(False)
        self.loginLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLineEdit.setGeometry(QtCore.QRect(1550, 0, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLineEdit.sizePolicy().hasHeightForWidth())
        self.loginLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OpenSymbol")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.loginLineEdit.setFont(font)
        self.loginLineEdit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.loginLineEdit.setText("")
        self.loginLineEdit.setMaxLength(13)
        self.loginLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(1550, 70, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.bar_rank_1 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_1.setGeometry(QtCore.QRect(1600, 430, 301, 51))
        self.bar_rank_1.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_1.setProperty("value", 0)
        self.bar_rank_1.setTextVisible(False)
        self.bar_rank_1.setInvertedAppearance(False)
        self.bar_rank_1.setObjectName("bar_rank_1")
        self.bar_rank_10 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_10.setGeometry(QtCore.QRect(1600, 970, 301, 51))
        self.bar_rank_10.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_10.setProperty("value", 0)
        self.bar_rank_10.setTextVisible(False)
        self.bar_rank_10.setInvertedAppearance(False)
        self.bar_rank_10.setObjectName("bar_rank_10")
        self.bar_rank_9 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_9.setGeometry(QtCore.QRect(1600, 910, 301, 51))
        self.bar_rank_9.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_9.setProperty("value", 0)
        self.bar_rank_9.setTextVisible(False)
        self.bar_rank_9.setInvertedAppearance(False)
        self.bar_rank_9.setObjectName("bar_rank_9")
        self.bar_rank_8 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_8.setGeometry(QtCore.QRect(1600, 850, 301, 51))
        self.bar_rank_8.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_8.setProperty("value", 0)
        self.bar_rank_8.setTextVisible(False)
        self.bar_rank_8.setInvertedAppearance(False)
        self.bar_rank_8.setObjectName("bar_rank_8")
        self.bar_rank_7 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_7.setGeometry(QtCore.QRect(1600, 790, 301, 51))
        self.bar_rank_7.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_7.setProperty("value", 0)
        self.bar_rank_7.setTextVisible(False)
        self.bar_rank_7.setInvertedAppearance(False)
        self.bar_rank_7.setObjectName("bar_rank_7")
        self.bar_rank_6 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_6.setGeometry(QtCore.QRect(1600, 730, 301, 51))
        self.bar_rank_6.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_6.setProperty("value", 0)
        self.bar_rank_6.setTextVisible(False)
        self.bar_rank_6.setInvertedAppearance(False)
        self.bar_rank_6.setObjectName("bar_rank_6")
        self.bar_rank_5 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_5.setGeometry(QtCore.QRect(1600, 670, 301, 51))
        self.bar_rank_5.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_5.setProperty("value", 0)
        self.bar_rank_5.setTextVisible(False)
        self.bar_rank_5.setInvertedAppearance(False)
        self.bar_rank_5.setObjectName("bar_rank_5")
        self.bar_rank_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_4.setGeometry(QtCore.QRect(1600, 610, 301, 51))
        self.bar_rank_4.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_4.setProperty("value", 0)
        self.bar_rank_4.setTextVisible(False)
        self.bar_rank_4.setInvertedAppearance(False)
        self.bar_rank_4.setObjectName("bar_rank_4")
        self.bar_rank_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_3.setGeometry(QtCore.QRect(1600, 550, 301, 51))
        self.bar_rank_3.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_3.setProperty("value", 0)
        self.bar_rank_3.setTextVisible(False)
        self.bar_rank_3.setInvertedAppearance(False)
        self.bar_rank_3.setObjectName("bar_rank_3")
        self.bar_rank_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_rank_2.setGeometry(QtCore.QRect(1600, 490, 301, 51))
        self.bar_rank_2.setStyleSheet(" QProgressBar::chunk {background-color: #e2a215; width: 1px;}\n"
"")
        self.bar_rank_2.setProperty("value", 0)
        self.bar_rank_2.setTextVisible(False)
        self.bar_rank_2.setInvertedAppearance(False)
        self.bar_rank_2.setObjectName("bar_rank_2")
        self.label_rank_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_1.setGeometry(QtCore.QRect(1550, 430, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_1.setFont(font)
        self.label_rank_1.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_1.setObjectName("label_rank_1")
        self.label_rank_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_2.setGeometry(QtCore.QRect(1550, 490, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_2.setFont(font)
        self.label_rank_2.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_2.setObjectName("label_rank_2")
        self.label_rank_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_3.setGeometry(QtCore.QRect(1550, 550, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_3.setFont(font)
        self.label_rank_3.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_3.setObjectName("label_rank_3")
        self.name_label_rank_1 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_1.setGeometry(QtCore.QRect(1610, 430, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_1.setFont(font)
        self.name_label_rank_1.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_1.setText("")
        self.name_label_rank_1.setObjectName("name_label_rank_1")
        self.label_rank_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_4.setGeometry(QtCore.QRect(1550, 610, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_4.setFont(font)
        self.label_rank_4.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_4.setObjectName("label_rank_4")
        self.label_rank_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_5.setGeometry(QtCore.QRect(1550, 670, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_5.setFont(font)
        self.label_rank_5.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_5.setObjectName("label_rank_5")
        self.label_rank_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_6.setGeometry(QtCore.QRect(1550, 730, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_6.setFont(font)
        self.label_rank_6.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_6.setObjectName("label_rank_6")
        self.label_rank_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_7.setGeometry(QtCore.QRect(1550, 790, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_7.setFont(font)
        self.label_rank_7.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_7.setObjectName("label_rank_7")
        self.label_rank_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_8.setGeometry(QtCore.QRect(1550, 850, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_8.setFont(font)
        self.label_rank_8.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_8.setObjectName("label_rank_8")
        self.label_rank_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_9.setGeometry(QtCore.QRect(1550, 910, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_9.setFont(font)
        self.label_rank_9.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_9.setObjectName("label_rank_9")
        self.label_rank_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_rank_10.setGeometry(QtCore.QRect(1550, 970, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_rank_10.setFont(font)
        self.label_rank_10.setStyleSheet("QLabel { color: rgb(10, 129, 10); background-color: rgba(255, 255, 255, 10) }")
        self.label_rank_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_rank_10.setObjectName("label_rank_10")
        self.name_label_rank_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_2.setGeometry(QtCore.QRect(1610, 490, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_2.setFont(font)
        self.name_label_rank_2.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_2.setText("")
        self.name_label_rank_2.setObjectName("name_label_rank_2")
        self.name_label_rank_3 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_3.setGeometry(QtCore.QRect(1610, 550, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_3.setFont(font)
        self.name_label_rank_3.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_3.setText("")
        self.name_label_rank_3.setObjectName("name_label_rank_3")
        self.name_label_rank_4 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_4.setGeometry(QtCore.QRect(1610, 610, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_4.setFont(font)
        self.name_label_rank_4.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_4.setText("")
        self.name_label_rank_4.setObjectName("name_label_rank_4")
        self.name_label_rank_5 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_5.setGeometry(QtCore.QRect(1610, 670, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_5.setFont(font)
        self.name_label_rank_5.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_5.setText("")
        self.name_label_rank_5.setObjectName("name_label_rank_5")
        self.name_label_rank_6 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_6.setGeometry(QtCore.QRect(1610, 730, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_6.setFont(font)
        self.name_label_rank_6.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_6.setText("")
        self.name_label_rank_6.setObjectName("name_label_rank_6")
        self.name_label_rank_7 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_7.setGeometry(QtCore.QRect(1610, 790, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_7.setFont(font)
        self.name_label_rank_7.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_7.setText("")
        self.name_label_rank_7.setObjectName("name_label_rank_7")
        self.name_label_rank_8 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_8.setGeometry(QtCore.QRect(1610, 850, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_8.setFont(font)
        self.name_label_rank_8.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_8.setText("")
        self.name_label_rank_8.setObjectName("name_label_rank_8")
        self.name_label_rank_9 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_9.setGeometry(QtCore.QRect(1610, 910, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_9.setFont(font)
        self.name_label_rank_9.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_9.setText("")
        self.name_label_rank_9.setObjectName("name_label_rank_9")
        self.name_label_rank_10 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_rank_10.setGeometry(QtCore.QRect(1610, 970, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.name_label_rank_10.setFont(font)
        self.name_label_rank_10.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.name_label_rank_10.setText("")
        self.name_label_rank_10.setObjectName("name_label_rank_10")
        self.time_label_rank_1 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_1.setGeometry(QtCore.QRect(1810, 430, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_1.setFont(font)
        self.time_label_rank_1.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_1.setText("")
        self.time_label_rank_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_1.setObjectName("time_label_rank_1")
        self.time_label_rank_2 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_2.setGeometry(QtCore.QRect(1810, 490, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_2.setFont(font)
        self.time_label_rank_2.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_2.setText("")
        self.time_label_rank_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_2.setObjectName("time_label_rank_2")
        self.time_label_rank_3 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_3.setGeometry(QtCore.QRect(1810, 550, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_3.setFont(font)
        self.time_label_rank_3.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_3.setText("")
        self.time_label_rank_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_3.setObjectName("time_label_rank_3")
        self.time_label_rank_4 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_4.setGeometry(QtCore.QRect(1810, 610, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_4.setFont(font)
        self.time_label_rank_4.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_4.setText("")
        self.time_label_rank_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_4.setObjectName("time_label_rank_4")
        self.time_label_rank_5 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_5.setGeometry(QtCore.QRect(1810, 670, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_5.setFont(font)
        self.time_label_rank_5.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_5.setText("")
        self.time_label_rank_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_5.setObjectName("time_label_rank_5")
        self.time_label_rank_6 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_6.setGeometry(QtCore.QRect(1810, 730, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_6.setFont(font)
        self.time_label_rank_6.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_6.setText("")
        self.time_label_rank_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_6.setObjectName("time_label_rank_6")
        self.time_label_rank_7 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_7.setGeometry(QtCore.QRect(1810, 790, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_7.setFont(font)
        self.time_label_rank_7.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_7.setText("")
        self.time_label_rank_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_7.setObjectName("time_label_rank_7")
        self.time_label_rank_8 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_8.setGeometry(QtCore.QRect(1810, 850, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_8.setFont(font)
        self.time_label_rank_8.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_8.setText("")
        self.time_label_rank_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_8.setObjectName("time_label_rank_8")
        self.time_label_rank_9 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_9.setGeometry(QtCore.QRect(1810, 910, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_9.setFont(font)
        self.time_label_rank_9.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_9.setText("")
        self.time_label_rank_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_9.setObjectName("time_label_rank_9")
        self.time_label_rank_10 = QtWidgets.QLabel(self.centralwidget)
        self.time_label_rank_10.setGeometry(QtCore.QRect(1810, 970, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.time_label_rank_10.setFont(font)
        self.time_label_rank_10.setStyleSheet("QLabel { color: rgb(6,175,6); background-color: rgba(0, 0, 0, 0) }")
        self.time_label_rank_10.setText("")
        self.time_label_rank_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label_rank_10.setObjectName("time_label_rank_10")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuPeople = QtWidgets.QMenu(self.menubar)
        self.menuPeople.setObjectName("menuPeople")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionView_Hours = QtWidgets.QAction(mainWindow)
        self.actionView_Hours.setObjectName("actionView_Hours")
        self.actionGenerate_Report = QtWidgets.QAction(mainWindow)
        self.actionGenerate_Report.setObjectName("actionGenerate_Report")
        self.actionAdd_Person = QtWidgets.QAction(mainWindow)
        self.actionAdd_Person.setObjectName("actionAdd_Person")
        self.actionSign_Out_All = QtWidgets.QAction(mainWindow)
        self.actionSign_Out_All.setObjectName("actionSign_Out_All")
        self.actionClear_All = QtWidgets.QAction(mainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionFullscreen = QtWidgets.QAction(mainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionExit_Fullscreen = QtWidgets.QAction(mainWindow)
        self.actionExit_Fullscreen.setObjectName("actionExit_Fullscreen")
        self.actionOptions = QtWidgets.QAction(mainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionRestart = QtWidgets.QAction(mainWindow)
        self.actionRestart.setObjectName("actionRestart")
        self.menuActions.addAction(self.actionSign_Out_All)
        self.menuActions.addAction(self.actionClear_All)
        self.menuPeople.addAction(self.actionAdd_Person)
        self.menuPeople.addSeparator()
        self.menuPeople.addAction(self.actionView_Hours)
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionGenerate_Report)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRestart)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_Fullscreen)
        self.menuFile.addAction(self.actionFullscreen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuPeople.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "PearLogger"))
        self.label_rank_1.setText(_translate("mainWindow", "1"))
        self.label_rank_2.setText(_translate("mainWindow", "2"))
        self.label_rank_3.setText(_translate("mainWindow", "3"))
        self.label_rank_4.setText(_translate("mainWindow", "4"))
        self.label_rank_5.setText(_translate("mainWindow", "5"))
        self.label_rank_6.setText(_translate("mainWindow", "6"))
        self.label_rank_7.setText(_translate("mainWindow", "7"))
        self.label_rank_8.setText(_translate("mainWindow", "8"))
        self.label_rank_9.setText(_translate("mainWindow", "9"))
        self.label_rank_10.setText(_translate("mainWindow", "10"))
        self.menuActions.setTitle(_translate("mainWindow", "Actions"))
        self.menuPeople.setTitle(_translate("mainWindow", "People"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.actionView_Hours.setText(_translate("mainWindow", "View Hours"))
        self.actionGenerate_Report.setText(_translate("mainWindow", "Generate Report"))
        self.actionAdd_Person.setText(_translate("mainWindow", "Add Person"))
        self.actionSign_Out_All.setText(_translate("mainWindow", "Sign Out All"))
        self.actionClear_All.setText(_translate("mainWindow", "Clear All"))
        self.actionFullscreen.setText(_translate("mainWindow", "Fullscreen"))
        self.actionExit_Fullscreen.setText(_translate("mainWindow", "Exit Fullscreen"))
        self.actionOptions.setText(_translate("mainWindow", "Options"))
        self.actionRestart.setText(_translate("mainWindow", "Restart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
